name: Build and Save Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image for multiple architectures
      run: |
        docker buildx create --use
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          -t yolo:latest \
          --output type=local,dest=./docker-output

    - name: Save Docker image as artifact
      run: |
        tar -czf yolo_latest.tar.gz -C ./docker-output .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yolo-docker-image
        path: yolo_latest.tar.gz